mywallet/mywallet/blueprints/category/__init__.py
"""Category Blueprint for CRUD views"""

from flask import Blueprint, request, session, url_for, redirect, \
    render_template, g, flash

from mywallet import models
from mywallet.decorators import login_required
from mywallet.forms.category import CategoryForm

bp = Blueprint('category', __name__, template_folder='templates')


@bp.route('/index', methods=['GET'])
@login_required
def index():
    """List all categories."""
    records = models.Category.query.all()
    return render_template('category/index.html',
                           modelname=models.Category.plural,
                           records=records)


@bp.route('/create', defaults={'id': None}, methods=['GET', 'POST'])
@bp.route('/create/<int:id>', methods=['GET', 'POST'])
@login_required
def create(id=None):
    """Create a new category."""
    title = 'New'
    record = models.Category()
    form = CategoryForm(request.form)
    if request.method == 'POST' and form.validate():
        form.populate_obj(record)
        models.db.session.add(record)
        models.db.session.commit()
        flash('Record created')
        return redirect(url_for('category.show', id=record.id))

    return render_template('category/form.html',
                           title=title,
                           modelname=models.Category.singular,
                           form=form,
                           record=record)


@bp.route('/update', defaults={'id': None}, methods=['GET', 'POST'])
@bp.route('/update/<int:id>', methods=['GET', 'POST'])
@login_required
def update(id=None):
    """Update an existing one."""
    title = 'Edit'
    record = models.Category.query.get_or_404(id)
    form = CategoryForm(request.form, obj=record)
    if request.method == 'POST' and form.validate():
        form.populate_obj(record)
        models.db.session.commit()
        flash('Record updated')
        return redirect(url_for('category.show', id=record.id))

    return render_template('category/form.html',
                           title=title,
                           modelname=models.Category.singular,
                           form=form,
                           record=record)


@bp.route('/show/<int:id>', methods=['GET'])
@login_required
def show(id):
    """Show details of a category."""
    record = models.Category.query.get_or_404(id)
    return render_template('category/show.html',
                           modelname=models.Category.singular,
                           record=record)


@bp.route('/delete/<int:id>', methods=['POST'])
@login_required
def delete(id):
    """Delete a category."""
    record = models.Category.query.get_or_404(id)
    models.db.session.delete(record)
    models.db.session.commit()
    flash('Record deleted')
    return redirect(url_for('category.index'))

mywallet/mywallet/blueprints/category/templates/category/actions.html
<a href="{{ url_for('category.show', id=record.id) }}">Details</a> |
<a href="{{ url_for('category.update', id=record.id) }}">Edit</a> |
<form action="{{ url_for('category.delete', id=record.id) }}" method="POST" style="display:inline; margin: 0; padding: 0;">
    <a href="#" onclick="$(this).closest('form').submit()">Delete</a>
</form>

mywallet/mywallet/blueprints/category/templates/category/form.html
{% extends "layout.html" %}

{% block title %}
  {{ modelname }} | {{ title }}
{% endblock %}

{% block body %}
  <h2>{{ modelname }}{% if record.id %} | {{ record.id }}{% endif %}</h2>
  {% include 'form_errors.html' %}

  <form action="" method="post">
    {{ form.csrf_token }}
    <dl>
      <dt>{{ form.code.label }}</dt>
      <dd>{{ form.code }}</dd>
      <dt>{{ form.name.label }}</dt>
      <dd>{{ form.name }}</dd>
      <dt>{{ form.description.label }}</dt>
      <dd>{{ form.description }}</dd>
    </dl>
    <div class="actions"><input type="submit" value="Submit"></div>
  </form>
{% endblock %}

mywallet/mywallet/blueprints/category/templates/category/index.html
{% extends "layout.html" %}

{% block title %}
  {{ modelname }}
{% endblock %}

{% block body %}
<a href="{{ url_for('category.create') }}">New</a>
<table border="1">
  <tbody>
    <tr>
      <th>ID</th>
      <th>Code</th>
      <th>Name</th>
      <th>Actions</th>
    </tr>
    {% for record in records %}
      <tr>
        <td>{{ record.id }}</td>
        <td>{{ record.code }}</td>
        <td>{{ record.name }}</td>
        <td>
          {% include 'category/actions.html' %}
        </td>
      </tr>
    {% else %}
      <tr>
        <td colspan="4">No record found.</td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
</table>
{% endblock %}

mywallet/mywallet/blueprints/category/templates/category/show.html
{% extends "layout.html" %}

{% block title %}
  {{ modelname }} | {{ record.id }}
{% endblock %}

{% block body %}
<table border="1">
  <tbody>
    <tr>
      <th>ID</th>
      <td>{{ record.id }}</td>
    </tr>
    <tr>
      <th>Code</th>
      <td>{{ record.code }}</td>
    </tr>
    <tr>
      <th>Name</th>
      <td>{{ record.name }}</td>
    </tr>
    <tr>
      <th>Description</th>
      <td>{{ record.description }}</td>
    </tr>
    <tr>
      <th>Created at</th>
      <td>{{ record.created_at }}</td>
    </tr>
    <tr>
      <th>Updated at</th>
      <td>{{ record.updated_at }}</td>
    </tr>
    <tr>
      <th>Actions</th>
      <td>{% include 'category/actions.html' %}</td>
    </tr>
  </tbody>
</table>
{% endblock %}