mywallet/mywallet/blueprints/user/__init__.py
"""User Blueprint for CRUD views"""

from flask import Blueprint, request, session, url_for, redirect, \
    render_template, g, flash
from werkzeug import check_password_hash, \
    generate_password_hash

from mywallet import constants, models
from mywallet.decorators import login_required
from mywallet.forms.user import LoginForm, RegistrationForm, UserForm

bp = Blueprint('user', __name__, template_folder='templates')


@bp.route('/index', methods=['GET'])
@login_required
def index():
    """List all users."""
    records = models.User.query.all()
    return render_template('user/index.html',
                           modelname=models.User.plural,
                           records=records,
                           guser=g.user)


@bp.route('/create', methods=['GET', 'POST'])
def create():
    """Registers the user."""
    if g.user:
        return redirect(url_for('index'))

    error = None
    form = RegistrationForm(request.form)
    if request.method == 'POST' and form.validate():
        if form.password.data == form.password2.data:
            if models.User.query.filter(
                    models.User.username == form.username.data).count() == 0:
                user = models.User(username=form.username.data,
                                   pw_hash=generate_password_hash(form.password.data),
                                   first_name=form.first_name.data,
                                   last_name=form.last_name.data,
                                   email=form.email.data)

                models.db.session.add(user)
                models.db.session.commit()

                flash('You were successfully registered and can login now')

                return redirect(url_for('login'))
            else:
                error = 'Username already taken'
        else:
            error = 'Passwords did not match'

    if error:
        flash(error)

    return render_template('user/register.html', form=form)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    """Logs the user in."""
    if g.user:
        return redirect(url_for('index'))

    form = LoginForm(request.form)
    error = None
    if request.method == 'POST' and form.validate():
        user = models.User.query.filter(models.User.username == form.username.data).first()

        if user is None:
            error = 'Invalid username'
        elif not check_password_hash(user.pw_hash, form.password.data):
            error = 'Invalid password'
        else:
            flash('You were logged in')
            session[constants.KEY_USERID] = user.id
            return redirect(url_for('index'))

    if error:
        flash(error)

    return render_template('user/login.html', form=form)


@bp.route('/logout')
def logout():
    """Logs the user out."""
    flash('You were logged out')

    session.pop(constants.KEY_USERID, None)

    return redirect(url_for('index'))

@bp.route('/update', methods=['GET', 'POST'])
@login_required
def update(id=None):
    """Update user profile."""
    record = g.user
    form = UserForm(request.form)
    if request.method == 'POST' and form.validate():
        if form.password.data == form.password2.data:
            if form.password.data:
                record.pw_hash = generate_password_hash(form.password.data)
            record.first_name = form.first_name.data
            record.last_name = form.last_name.data
            record.email = form.email.data
            models.db.session.commit()

            flash('Your profile updated')
            return redirect(url_for('user.show', id=record.id))

    return render_template('user/profileform.html',
                           form=form,
                           record=record)


@bp.route('/show/<int:id>', methods=['GET'])
@login_required
def show(id):
    """Show details of a user."""
    record = models.User.query.get_or_404(id)
    return render_template('user/show.html',
                           modelname=models.User.singular,
                           record=record,
                           guser=g.user)


@bp.route('/delete', methods=['POST'])
@login_required
def delete():
    """Delete a user."""
    record = g.user
    models.db.session.delete(record)
    models.db.session.commit()
    flash('Your account deleted')
    return redirect(url_for('index'))

mywallet/mywallet/blueprints/user/templates/user/actions.html
<a href="{{ url_for('user.show', id=record.id) }}">Details</a>
{% if guser == record %}
  | <a href="{{ url_for('user.update') }}">Edit</a> |
  <form action="{{ url_for('user.delete') }}" method="POST" style="display:inline; margin: 0; padding: 0;">
      <a href="#" onclick="$(this).closest('form').submit()">Delete</a>
  </form>
{% endif %}

mywallet/mywallet/blueprints/user/templates/user/index.html
{% extends "layout.html" %}

{% block title %}
  {{ modelname }}
{% endblock %}

{% block body %}
<table border="1">
  <tbody>
    <tr>
      <th>ID</th>
      <th>Username</th>
      <th>Is Active?</th>
      <th>Is Admin?</th>
      <th>Actions</th>
    </tr>
    {% for record in records %}
      <tr>
        <td>{{ record.id }}</td>
        <td>{{ record.username }}</td>
        <td>{{ record.is_active }}</td>
        <td>{{ record.is_admin }}</td>
        <td>
          {% include 'user/actions.html' %}
        </td>
      </tr>
    {% else %}
      <tr>
        <td colspan="3">No record found.</td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
</table>
{% endblock %}

mywallet/mywallet/blueprints/user/templates/user/login.html
{% extends "layout.html" %}

{% block title %}Sign In{% endblock %}

{% block body %}
  <h2>Sign In</h2>
  {% include 'form_errors.html' %}

  <form action="" method="post">
    {{ form.csrf_token }}
    <dl>
      <dt>{{ form.username.label }}</dt>
      <dd>{{ form.username }}</dd>
      <dt>{{ form.password.label }}</dt>
      <dd>{{ form.password }}</dd>
    </dl>
    <div class="actions"><input type="submit" value="Sign In"></div>
  </form>
{% endblock %}

mywallet/mywallet/blueprints/user/templates/user/profileform.html
{% extends "layout.html" %}

{% block title %}Profile{% endblock %}

{% block body %}
  <h2>Update Profile</h2>
  {% include 'form_errors.html' %}

  <form action="" method="post">
    {{ form.csrf_token }}
    <dl>
      <dt>{{ form.username.label }}</dt>
      <dd>{{ form.username(value=record.username, disabled=True) }}</dd>
      <dt>{{ form.password.label }}</dt>
      <dd>{{ form.password }}</dd>
      <dt>{{ form.password2.label }}</dt>
      <dd>{{ form.password2 }}</dd>
      <dt>{{ form.first_name.label }}</dt>
      <dd>{{ form.first_name(value=record.first_name) }}</dd>
      <dt>{{ form.last_name.label }}</dt>
      <dd>{{ form.last_name(value=record.last_name) }}</dd>
      <dt>{{ form.email.label }}</dt>
      <dd>{{ form.email(value=record.email) }}</dd>
    </dl>
    <div class="actions"><input type="submit" value="Submit"></div>
  </form>
{% endblock %}

mywallet/mywallet/blueprints/user/templates/user/register.html
{% extends "layout.html" %}
{% block title %}Welcome!{% endblock %}
{% block body %}
  <h2>Sign Up</h2>
  {% include 'form_errors.html' %}

  <form action="" method="post">
    {{ form.csrf_token }}
    <dl>
      <dt>{{ form.username.label }}</dt>
      <dd>{{ form.username }}</dd>

      <dt>{{ form.password.label }}</dt>
      <dd>{{ form.password }}</dd>

      <dt>{{ form.password2.label }}</dt>
      <dd>{{ form.password2 }}</dd>

      <br/>

      <dt>{{ form.first_name.label }}</dt>
      <dd>{{ form.first_name }}</dd>

      <dt>{{ form.last_name.label }}</dt>
      <dd>{{ form.last_name }}</dd>

      <dt>{{ form.email.label }}</dt>
      <dd>{{ form.email }}</dd>
      
    </dl>
    <div class="actions"><input type="submit" value="Sign Up" /></div>
  </form>
{% endblock %}

mywallet/mywallet/blueprints/user/templates/user/show.html
{% extends "layout.html" %}

{% block title %}
  {{ modelname }} | {{ record.id }}
{% endblock %}

{% block body %}
<table border="1">
  <tbody>
    <tr>
      <th>ID</th>
      <td>{{ record.id }}</td>
    </tr>
    <tr>
      <th>Username</th>
      <td>{{ record.username }}</td>
    </tr>
    <tr>
      <th>First Name</th>
      <td>{{ record.first_name }}</td>
    </tr>
    <tr>
      <th>Last Name</th>
      <td>{{ record.last_name }}</td>
    </tr>
    <tr>
      <th>Email</th>
      <td>{{ record.email }}</td>
    </tr>
    <tr>
      <th>Is Active</th>
      <td>{{ record.is_active }}</td>
    </tr>
    <tr>
      <th>Is Admin</th>
      <td>{{ record.is_admin }}</td>
    </tr>
    <tr>
      <th>Created at</th>
      <td>{{ record.created_at }}</td>
    </tr>
    <tr>
      <th>Updated at</th>
      <td>{{ record.updated_at }}</td>
    </tr>
    <tr>
      <th>Actions</th>
      <td>{% include 'user/actions.html' %}</td>
    </tr>
  </tbody>
</table>
{% endblock %}