mywallet/mywallet/blueprints/tag/__init__.py
"""Tag Blueprint for CRUD views"""

from flask import Blueprint, request, session, url_for, redirect, \
    render_template, g, flash

from mywallet import models
from mywallet.decorators import login_required
from mywallet.forms.tag import TagForm

bp = Blueprint('tag', __name__, template_folder='templates')


@bp.route('/index', methods=['GET'])
@login_required
def index():
    """List all tags."""
    records = models.Tag.query.all()
    return render_template('tag/index.html',
                           modelname=models.Tag.plural,
                           records=records)


@bp.route('/create', defaults={'id': None}, methods=['GET', 'POST'])
@bp.route('/create/<int:id>', methods=['GET', 'POST'])
@login_required
def create(id=None):
    """Create a new tag."""
    title = 'New'
    record = models.Tag()
    form = TagForm(request.form)
    if request.method == 'POST' and form.validate():
        form.populate_obj(record)
        models.db.session.add(record)
        models.db.session.commit()
        flash('Record created')
        return redirect(url_for('tag.show', id=record.id))

    return render_template('tag/form.html',
                           title=title,
                           modelname=models.Tag.singular,
                           form=form,
                           record=record)


@bp.route('/update', defaults={'id': None}, methods=['GET', 'POST'])
@bp.route('/update/<int:id>', methods=['GET', 'POST'])
@login_required
def update(id=None):
    """Update an existing one."""
    title = 'Edit'
    record = models.Tag.query.get_or_404(id)
    form = TagForm(request.form, obj=record)
    if request.method == 'POST' and form.validate():
        form.populate_obj(record)
        models.db.session.commit()
        flash('Record updated')
        return redirect(url_for('tag.show', id=record.id))

    return render_template('tag/form.html',
                           title=title,
                           modelname=models.Tag.singular,
                           form=form,
                           record=record)


@bp.route('/show/<int:id>', methods=['GET'])
@login_required
def show(id):
    """Show details of a tag."""
    record = models.Tag.query.get_or_404(id)
    return render_template('tag/show.html',
                           modelname=models.Tag.singular,
                           record=record)


@bp.route('/delete/<int:id>', methods=['POST'])
@login_required
def delete(id):
    """Delete a tag."""
    record = models.Tag.query.get_or_404(id)
    models.db.session.delete(record)
    models.db.session.commit()
    flash('Record deleted')
    return redirect(url_for('tag.index'))

mywallet/mywallet/blueprints/tag/templates/tag/actions.html
<a href="{{ url_for('tag.show', id=record.id) }}">Details</a> |
<a href="{{ url_for('tag.update', id=record.id) }}">Edit</a> |
<form action="{{ url_for('tag.delete', id=record.id) }}" method="POST" style="display:inline; margin: 0; padding: 0;">
    <a href="#" onclick="$(this).closest('form').submit()">Delete</a>
</form>

mywallet/mywallet/blueprints/tag/templates/tag/form.html
{% extends "layout.html" %}

{% block title %}
  {{ modelname }} | {{ title }}
{% endblock %}

{% block body %}
  <h2>{{ modelname }}{% if record.id %} | {{ record.id }}{% endif %}</h2>
  {% include 'form_errors.html' %}

  <form action="" method="post">
    {{ form.csrf_token }}
    <dl>
      <dt>{{ form.name.label }}</dt>
      <dd>{{ form.name }}</dd>
      <dt>{{ form.description.label }}</dt>
      <dd>{{ form.description }}</dd>
    </dl>
    <div class="actions"><input type="submit" value="Submit"></div>
  </form>
{% endblock %}

mywallet/mywallet/blueprints/tag/templates/tag/index.html
{% extends "layout.html" %}

{% block title %}
  {{ modelname }}
{% endblock %}

{% block body %}
<a href="{{ url_for('tag.create') }}">New</a>
<table border="1">
  <tbody>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Actions</th>
    </tr>
    {% for record in records %}
      <tr>
        <td>{{ record.id }}</td>
        <td>{{ record.name }}</td>
        <td>
          {% include 'tag/actions.html' %}
        </td>
      </tr>
    {% else %}
      <tr>
        <td colspan="3">No record found.</td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
</table>
{% endblock %}

mywallet/mywallet/blueprints/tag/templates/tag/show.html
{% extends "layout.html" %}

{% block title %}
  {{ modelname }} | {{ record.id }}
{% endblock %}

{% block body %}
<table border="1">
  <tbody>
    <tr>
      <th>ID</th>
      <td>{{ record.id }}</td>
    </tr>
    <tr>
      <th>Name</th>
      <td>{{ record.name }}</td>
    </tr>
    <tr>
      <th>Description</th>
      <td>{{ record.description }}</td>
    </tr>
    <tr>
      <th>Created at</th>
      <td>{{ record.created_at }}</td>
    </tr>
    <tr>
      <th>Updated at</th>
      <td>{{ record.updated_at }}</td>
    </tr>
    <tr>
      <th>Actions</th>
      <td>{% include 'tag/actions.html' %}</td>
    </tr>
  </tbody>
</table>
{% endblock %}